name: Automatically deploy to nest

on: [push]

jobs:
  
  deploy-to-nest:
      runs-on: ubuntu-latest
      steps:
      - name: Connect to ssh, pull and systemctl restart
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            : # Load nix binaries
            export PATH=/home/vic/.nix-profile/bin:$PATH
            export PATH=/nix/var/nix/profiles/default/bin:$PATH
            cd /home/vic/slack-only-once
            git pull
            systemctl restart OnlyOnce.service